repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.10

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-builtins, pep8-naming, flake8-comments]

-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy

-   repo: https://github.com/fpgmaas/deptry
    rev: 0.11.0
    hooks:
    -   id: deptry