# Generated by Django 4.2.2 on 2023-07-02 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("employees_number", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Intern", "Intern"),
                            ("Junior", "Junior"),
                            ("Middle", "Middle"),
                            ("Senior", "Senior"),
                        ],
                        max_length=10,
                    ),
                ),
                ("expirience", models.CharField(max_length=30)),
                ("min_salary", models.PositiveIntegerField(null=True)),
                ("max_salary", models.PositiveIntegerField(null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        related_query_name="vacancy",
                        to="core.company",
                    ),
                ),
            ],
        ),
    ]
