# Generated by Django 4.2.2 on 2023-07-02 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="company",
            table="companies",
        ),
        migrations.AlterModelTable(
            name="vacancy",
            table="vacancies",
        ),
    ]
