# Generated by Django 4.2.2 on 2023-07-06 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_company_table_alter_vacancy_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "levels",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "tags",
            },
        ),
        migrations.AddField(
            model_name="vacancy",
            name="tags",
            field=models.ManyToManyField(db_table="vacancies_tags", related_name="vacancies", to="core.tag"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="vacancy", to="core.level"
            ),
        ),
    ]
