# Generated by Django 4.2.3 on 2023-07-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_level_name_alter_tag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="attachment",
            field=models.FileField(null=True, upload_to="vacancies/attachments/"),
        ),
    ]
