# Generated by Django 4.2.3 on 2023-08-15 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_emailconfirmationcodes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vacancy",
            options={"permissions": [("apply_to_vacancy", "Allows apply to any vacancy")]},
        ),
    ]
