# Generated by Django 4.2.3 on 2023-08-15 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0012_add_apply_to_vacancy_permission_for_candidate"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("note", models.CharField(max_length=1000)),
                ("cv", models.FileField(null=True, upload_to="users/cvs/")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="job_responses", to="core.vacancy"
                    ),
                ),
            ],
            options={
                "db_table": "job_responses",
            },
        ),
    ]
