# Generated by Django 4.2.3 on 2023-10-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_jobresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="qr_code",
            field=models.ImageField(null=True, upload_to="vacancies/qr/"),
        ),
    ]
